import { z } from "zod";
import {
  Answer,
  answerSchema,
  RED_FLAG_DEFINITIONS,
  RED_FLAG_KEYS,
  RED_FLAG_LABELS,
  RedFlagDefinition,
  RedFlagKey,
  redFlagsSchema,
  RedFlags,
} from "./red-flags";

// Re-export red-flag and answer primitives
export {
  RED_FLAG_DEFINITIONS,
  RED_FLAG_KEYS,
  RED_FLAG_LABELS,
  answerSchema,
  redFlagsSchema,
};
export type { Answer, RedFlagDefinition, RedFlagKey, RedFlags };

/**
 * Reviewed intake schema and type as defined in sickway.md §8.
 *
 * Missing-vs-negative semantics:
 * - medsTaken: [] means explicitly none; null means unanswered / unknown.
 * - allergies: [] means explicitly none; null means unanswered / unknown.
 * - redFlags: every checklist key must have an explicit Answer (true | false | null).
 * - onsetIso: null means unknown onset time; onsetConfirmed captures explicit confirmation.
 * - deadlineToday: null means no deadline reported.
 * - No dorm field is collected.
 */
export const reviewedIntakeSchema = z.object({
  symptoms: z.array(z.string()),
  onsetIso: z.string().nullable(),
  onsetConfirmed: z.boolean(),
  maxTempF: z.number().nullable(),
  medsTaken: z.array(z.string()).nullable(),
  allergies: z.array(z.string()).nullable(),
  redFlags: redFlagsSchema,
  deadlineToday: z.string().nullable(),
  transcript: z.string(),
});
export type ReviewedIntake = z.infer<typeof reviewedIntakeSchema>;

/**
 * Consent schema: shareWithClinic must be literal true.
 * Consent is modeled as literal true; there is no encounter shape without consent.
 */
export const consentSchema = z.object({
  shareWithClinic: z.literal(true),
  capturedAt: z.string(),
});
export type Consent = z.infer<typeof consentSchema>;

/**
 * Field sources indicating provenance for intake fields (§6.1).
 */
export const fieldSourceSchema = z.enum([
  "synthetic_profile",
  "student_review",
  "demo_fixture",
]);
export type FieldSource = z.infer<typeof fieldSourceSchema>;

/**
 * SBAR source provenance: generated by model, deterministic fallback, or prepared fixture.
 */
export const sbarSourceSchema = z.enum([
  "generated",
  "deterministic",
  "prepared_fixture",
]);
export type SbarSource = z.infer<typeof sbarSourceSchema>;

/**
 * SBAR brief output schema (§7.2, §8).
 */
export const sbarSchema = z.object({
  situation: z.string(),
  background: z.string(),
  assessment: z.string(),
  recommendation: z.string(),
  spokenScript: z.string(),
  source: sbarSourceSchema,
});
export type Sbar = z.infer<typeof sbarSchema>;

/**
 * Encounter status as defined in §8.
 */
export const encounterStatusSchema = z.enum([
  "needs_review",
  "emergency",
  "ready",
  "in_visit",
  "packet_available",
]);
export type EncounterStatus = z.infer<typeof encounterStatusSchema>;

/**
 * Optional simulated follow-up self-report (§7.6, §8).
 */
export const followUpSchema = z.object({
  simulated: z.literal(true),
  filled: z.boolean(),
  symptomStatus: z.string(),
});
export type FollowUp = z.infer<typeof followUpSchema>;

/**
 * Synthetic profile ID guardrail: only demo-student-01 is valid in this prototype.
 */
export const DEMO_PROFILE_ID = "demo-student-01" as const;
export const demoProfileIdSchema = z.literal(DEMO_PROFILE_ID);

/**
 * Encounter schema as defined in sickway.md §8.
 */
export const encounterSchema = z.object({
  id: z.string().min(1),
  demoSessionId: z.string().min(1),
  profileId: demoProfileIdSchema,
  createdAt: z.string(),
  status: encounterStatusSchema,
  intake: reviewedIntakeSchema,
  consent: consentSchema,
  fieldSources: z.record(z.string(), fieldSourceSchema),
  sbar: sbarSchema.optional(),
  unlockedTherapyIds: z.array(z.string()),
  /**
   * The student's own choice of instruction languages (issue #61). Optional: absent means the
   * student did not choose and the profile's displayed selection applies. The clinician still
   * confirms the packet's languages.
   */
  preferredInstructionLanguages: z.array(z.enum(["en", "es"])).min(1).optional(),
  chosenTherapyId: z.string().optional(),
  packetId: z.string().optional(),
  followUp: followUpSchema.optional(),
});
export type Encounter = z.infer<typeof encounterSchema>;

/**
 * Instruction languages supported for student return packet.
 */
export const instructionLanguageSchema = z.enum(["en", "es"]);
export type InstructionLanguage = z.infer<typeof instructionLanguageSchema>;

/**
 * Packet status literal.
 */
export const packetStatusSchema = z.literal("available_in_demo");
export type PacketStatus = z.infer<typeof packetStatusSchema>;

/**
 * Packet record schema as defined in §7.5, §8.
 */
export const packetSchema = z.object({
  id: z.string().min(1),
  demoSessionId: z.string().min(1),
  encounterId: z.string().min(1),
  therapyId: z.string().min(1),
  pharmacyId: z.string().min(1),
  mockPrice: z.number().nonnegative(),
  resourceIds: z.array(z.string()),
  instructionLanguages: z.array(instructionLanguageSchema).min(1),
  createdAt: z.string(),
  status: packetStatusSchema,
});
export type Packet = z.infer<typeof packetSchema>;

/**
 * Demo session schema for two-device pairing and session isolation (§8).
 */
export const demoSessionSchema = z.object({
  id: z.string().min(1),
  profileId: demoProfileIdSchema,
  fixtureClock: z.string(),
  createdAt: z.string(),
  ttl: z.number(),
});
export type DemoSession = z.infer<typeof demoSessionSchema>;

/**
 * Audit event record schema for manufacturer resource unlock logging (§7.4, §8).
 */
export const auditEventSchema = z.object({
  id: z.string().min(1),
  demoSessionId: z.string().min(1),
  encounterId: z.string().min(1),
  timestamp: z.string(),
  action: z.string().min(1),
  therapyId: z.string().min(1),
  resourceIds: z.array(z.string()),
  reason: z.string().min(1),
  ttl: z.number().optional(),
});
export type AuditEvent = z.infer<typeof auditEventSchema>;

/**
 * Option row schema representing joined therapy, formulary, and pharmacy access (§7.3, §8).
 * Every price, coverage, and stock value carries an explicit mock flag.
 */
export const optionRowSchema = z.object({
  therapyId: z.string().min(1),
  therapyName: z.string().min(1),
  generic: z.boolean(),
  formularyTier: z.string().min(1),
  coverageStatus: z.string().min(1),
  coverageMock: z.literal(true),
  estimatedCost: z.number().nonnegative(),
  costMock: z.literal(true),
  exceedsCostCeiling: z.boolean(),
  pharmacyId: z.string().min(1),
  pharmacyName: z.string().min(1),
  stockStatus: z.string().min(1),
  stockMock: z.literal(true),
  hasManufacturerResources: z.boolean(),
  resourceMock: z.literal(true).optional(),
});
export type OptionRow = z.infer<typeof optionRowSchema>;

/**
 * Manufacturer resource schema (§7.4).
 * Always explicitly labelled as fictional demo resource.
 */
export const manufacturerResourceSchema = z.object({
  id: z.string().min(1),
  therapyId: z.string().min(1),
  type: z.enum(["copay_card", "educational", "other"]),
  title: z.string().min(1),
  description: z.string().min(1),
  mockLabel: z.literal("Manufacturer resource — fictional demo"),
  url: z.string().optional(),
});
export type ManufacturerResource = z.infer<typeof manufacturerResourceSchema>;
